epochs: 20
seed: 1234
use_cuda: true
mixed_precision: true
label_smoothing: 0.0
max_grad_norm: 1.0
optimizer:
  name: AdamW
  params:
    lr: 0.001
    weight_decay: 0.01
scheduler:
  name: CosineAnnealingLR
  params:
    T_max: ${training.epochs}
    eta_min: 1e-5
log_interval: 50
eval_interval: 1
sweep:
  metric: validation/accuracy
  mode: max
