_wandb:
    value:
        cli_version: 0.22.2
        e:
            8eo4by5pqwhqrxxcjpa5krh7mgz7xl88:
                apple:
                    ecpuCores: 4
                    gpuCores: 38
                    memoryGb: 32
                    name: Apple M2 Max
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                    swapTotalBytes: "6442450944"
                codePath: notebooks/03b_extended_pytorch_tests.ipynb
                codePathLocal: 03b_extended_pytorch_tests.ipynb
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "538254798848"
                email: ericwkoch@gmail.com
                executable: /usr/local/anaconda3/envs/mlp/bin/python
                git:
                    commit: d2a4a86edece45df4d717680d0d88921295bdfb0
                    remote: https://github.com/erickoch3/mlpractical.git
                host: Erics-MacBook-Pro-1267.local
                memory:
                    total: "34359738368"
                os: macOS-26.0.1-arm64-arm-64bit
                program: /Users/ewkoch/repos/mlp/notebooks/03b_extended_pytorch_tests.ipynb
                python: CPython 3.12.11
                root: /Users/ewkoch/repos/mlp/notebooks
                startedAt: "2025-10-10T12:43:38.905969Z"
                writerId: 8eo4by5pqwhqrxxcjpa5krh7mgz7xl88
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.12.11
            "5": 0.22.2
            "8":
                - 1
            "12": 0.22.2
            "13": darwin-arm64
augment:
    value: true
batch_size:
    value: 256
data_dir:
    value: null
dropout:
    value: 0.25
epochs:
    value: 20
gradient_clip:
    value: 1
hidden_units:
    value:
        - 1024
        - 512
        - 256
label_smoothing:
    value: 0.05
learning_rate:
    value: 0.005
max_lr:
    value: 0.03
mixup_alpha:
    value: 0.1
run_name:
    value: onecycle_mixup_label_smoothing
valid_split:
    value: 8000
wandb_project:
    value: mlp-mnist-extended
weight_decay:
    value: 0.0001
